server:
  port: 8080
  servlet:
    context-path: /
spring:
#  MySQL配置
#  datasource:
#    username: root
#    password: Aa123!@#
#    url: jdbc:mysql://localhost:3306/dataPlatform?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    username: root
    password: root
    url: jdbc:hive2://192.168.0.109:10000/dataplatform
    driverClassName: org.apache.hive.jdbc.HiveDriver

thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
